services:
  - type: web
    name: anime-recommender-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main_api:app --host 0.0.0.0 --port $PORT
    plan: free
